    - name: Deploy BlackChat to VPS
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} "
        set -e  # Exit immediately if a command exits with a non-zero status.
        
        # Install python3-venv package if not already installed
        sudo apt update && sudo apt install -y python3-venv &&

        # Create the project directory if it doesn't exist
        mkdir -p /home/projects/BlackChat &&
        cd /home/projects/BlackChat &&
        
        # If there's no git repository, clone it
        if [ ! -d .git ]; then
          git clone https://github.com/ministerko/BlackChat.git .;
        fi &&
        
        # Pull the latest code from the master branch
        git pull origin master &&
        
        # Create a virtual environment if it doesn't exist
        if [ ! -d venv ]; then
          python3 -m venv venv;
        fi &&
        
        # Verify virtual environment creation
        echo 'Checking virtual environment directory:'
        ls -la venv &&
        
        # Activate the virtual environment and install dependencies
        source venv/bin/activate &&
        python --version &&
        pip install --upgrade pip &&
        pip install -r requirements.txt
    - name: Restart FastAPI service
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} "
        sudo systemctl restart blackchat
        "
